export const english: Record<string, string> = {
  brand: 'KYC KIT', secureCapture: 'Guided face capture', captureOnly: 'Your camera stops after capture',
  introTitle: 'Take a quick selfie', introBody: 'Follow a few simple movements. Your capture starts automatically.',
  identityTitle: 'Verify your identity', identityBody: 'Photograph your document, then follow the face guide.', documentBegin: 'Choose document', back: 'Back',
  introEyebrow: 'LET’S GET YOU READY', goodLight: 'Find a well-lit space', goodLightBody: 'Face a light source and keep your face visible.',
  cameraReady: 'Use your front camera', cameraReadyBody: 'Camera access starts when you choose to begin.',
  natural: 'Keep your face clearly visible', naturalBody: 'Follow the guide and hold each position briefly.',
  start: 'Start face capture', cancel: 'Cancel', retake: 'Retake photo', confirm: 'Confirm & continue', retry: 'Try again',
  faceTitle: 'Follow the guide', faceBody: 'Keep your face inside the circle.',
  startCamera: 'Start camera', requesting: 'Opening your camera…', loading: 'Preparing face tracking…',
  cameraIdle: 'Camera off', cameraIdleBody: 'Start your camera when you’re ready.',
  center: 'Look straight ahead', 'turn-left': 'Turn your head to your left', 'turn-right': 'Turn your head to your right',
  'look-up': 'Tilt your head up', 'look-down': 'Tilt your head down', closer: 'Move a little closer', further: 'Move a little further away',
  'no-face': 'Bring your face into the circle', 'multiple-faces': 'Only one person should be in the frame',
  'center-face': 'Center your face inside the circle', 'neutral-pose': 'Face the camera straight on',
  'hold-still': 'Hold this position', 'move-closer': 'Move a little closer', 'move-further': 'Move a little further away',
  complete: 'Face forward for your selfie', capturing: 'Capturing your selfie…', hold: 'Hold briefly', step: 'Step', of: 'of',
  challengeList: 'Capture movements', faceProgress: 'Position hold progress', returnCenter: 'Come back to the center',
  automaticCapture: 'Your photo is taken automatically.',
  finishingVideo: 'Preparing your video…',
  videoReviewTitle: 'Check your video', videoReviewBody: 'Make sure your face is clearly visible throughout.',
  videoAlt: 'Your recorded face video', videoRetake: 'Record again',
  videoUnsupported: 'This browser cannot record face video. Use a supported browser and try again.',
  videoRecordingFailed: 'The video could not be recorded. Please try again.',
  videoTooLarge: 'The video reached its size limit. Try again and follow the guide promptly.',
  videoRecordingTimeout: 'The video recording timed out. Try again and follow the guide.',
  reviewTitle: 'Check your selfie', reviewBody: 'Make sure your face is clear and easy to see.',
  reviewEyebrow: 'REVIEW YOUR SELFIE', selfieAlt: 'Your captured selfie', photoReady: 'Photo ready',
  photoReadyBody: 'Confirm your selfie to continue, or retake the photo.',
  submittingTitle: 'Sending your capture', submittingBody: 'Please keep this page open for a moment.',
  processingTitle: 'Preparing your capture', matchingTitle: 'Comparing your photos', matchingBody: 'The comparison runs on your device. This may take a moment.',
  faceMatch: 'The faces look similar', faceNoMatch: 'The faces do not match', faceInconclusive: 'The photos could not be compared reliably',
  faceMatchBody: 'Photo similarity is one part of an identity check.', faceMatchSimulation: 'Face comparison is skipped in simulation mode.',
  matchingErrorBody: 'The comparison could not finish. Your photos are kept for another attempt.', faceComparisonUnavailable: 'Photo comparison is unavailable. Try again or ask for assistance.',
  resultTitle: 'Your capture is complete.', resultBody: 'Your capture is ready for the next step.', resultStatus: 'Capture complete',
  resultEyebrow: 'CAPTURE COMPLETE', errorTitle: 'Let’s try that again.', cameraErrorBody: 'We could not complete the face capture. Check the message below and try again.',
  submissionErrorBody: 'We could not send your capture. It is kept for another attempt.',
  permissionDenied: 'Camera permission was denied. Allow camera access in your browser, then try again.',
  cameraMissing: 'No usable camera was found. Connect a camera and try again.',
  cameraBusy: 'Your camera is unavailable. Close other apps using it and try again.',
  cameraUnsupported: 'Camera capture needs a supported browser and a secure HTTPS connection.',
  cameraTimeout: 'The face capture timed out. Try again in good lighting and follow the guide.',
  simulation: 'SIMULATION · DEMO ONLY', simulationBody: 'Synthetic movements and generated demo media. No camera, identity check, or liveness verification.',
  simulationStep: 'Simulate this movement', simulationStart: 'Start simulation', simulationFace: 'DEMO FACE',
  simulationIdleBody: 'Start the simulation when you’re ready.',
  cancelledTitle: 'Capture cancelled', cancelledBody: 'You can close this panel.', configError: 'Invalid capture configuration',
  documentSelectTitle: 'Choose your document', documentSelectBody: 'Use a valid, original document.',
  documentTypeIdCard: 'Identity card', documentTypeDriversLicense: 'Driver’s license', documentTypePassport: 'Passport', documentFrontAndBack: 'Front and back', documentPhotoPage: 'Photo page',
  documentFrontTitle: 'Photograph the front', documentFrontBody: 'Keep all four corners visible. Avoid blur and glare.',
  documentBackTitle: 'Photograph the back', documentBackBody: 'Turn your document over and keep all four corners visible.',
  documentPassportTitle: 'Photograph the photo page', documentCameraBody: 'Fit your document inside the frame. Avoid glare.',
  documentReviewTitle: 'Check your photo', documentReviewBody: 'Make sure every detail is clear and easy to read.',
  documentFrontAlt: 'Photograph of the front of your document', documentBackAlt: 'Photograph of the back of your document',
  documentContinue: 'Continue', documentStartCamera: 'Open camera', documentStartDemo: 'Continue', documentTakePhoto: 'Take photo', documentRetake: 'Retake photo', documentConfirm: 'Looks good',
  documentCaptureFailed: 'The document photo could not be captured. Try again.', documentCameraUnavailable: 'Your document camera is unavailable. Try again.',
  documentSearching: 'Keep all four corners inside the frame.', documentOutside: 'Move the whole document inside the frame.', documentTooSmall: 'Move a little closer.',
  documentDark: 'Use brighter, even lighting.', documentGlare: 'Tilt slightly to avoid reflections.', documentBlur: 'Hold steady and let the camera focus.',
  documentHoldStill: 'Hold steady…', documentReady: 'Looks clear. Take your photo.', documentGuidanceUnavailable: 'Keep all four corners visible. Check the photo after capture.',
  documentAutoHoldStill: 'Hold steady… taking your photo automatically.', documentAutoReady: 'Taking your photo automatically…', documentAutoProgress: 'Automatic photo capture',
};

const german: Record<string, string> = {
  brand: 'KYC KIT', secureCapture: 'Geführte Gesichtsaufnahme', captureOnly: 'Ihre Kamera stoppt nach der Aufnahme',
  introTitle: 'Ein kurzes Selfie', introBody: 'Ein paar einfache Bewegungen für ein klares Foto.',
  identityTitle: 'Identität bestätigen', identityBody: 'Fotografieren Sie Ihr Dokument und nehmen Sie ein Selfie auf.', documentBegin: 'Dokument auswählen', back: 'Zurück',
  introEyebrow: 'BEREIT FÜR DIE AUFNAHME', goodLight: 'Einen gut beleuchteten Ort wählen', goodLightBody: 'Schauen Sie in Richtung einer Lichtquelle. Ihr Gesicht sollte gut sichtbar sein.',
  cameraReady: 'Frontkamera verwenden', cameraReadyBody: 'Der Kamerazugriff beginnt erst, wenn Sie starten.',
  natural: 'Gesicht gut sichtbar halten', naturalBody: 'Folgen Sie den Hinweisen und halten Sie jede Position kurz.',
  start: 'Gesichtsaufnahme starten', cancel: 'Abbrechen', retake: 'Foto wiederholen', confirm: 'Bestätigen & weiter', retry: 'Erneut versuchen',
  faceTitle: 'Folgen Sie den Hinweisen', faceBody: 'Halten Sie Ihr Gesicht im Kreis.',
  startCamera: 'Kamera starten', requesting: 'Warten auf Kamerazugriff…', loading: 'Gesichtserkennung wird vorbereitet…',
  cameraIdle: 'Kamera aus', cameraIdleBody: 'Starten Sie die Kamera, wenn Sie bereit sind.',
  center: 'Geradeaus schauen', 'turn-left': 'Kopf nach links drehen', 'turn-right': 'Kopf nach rechts drehen',
  'look-up': 'Kopf nach oben neigen', 'look-down': 'Kopf nach unten neigen', closer: 'Etwas näher kommen', further: 'Etwas weiter weg bewegen',
  'no-face': 'Bringen Sie Ihr Gesicht in den Kreis', 'multiple-faces': 'Es darf nur eine Person im Bild sein',
  'center-face': 'Positionieren Sie Ihr Gesicht mittig im Kreis', 'neutral-pose': 'Schauen Sie gerade in die Kamera',
  'hold-still': 'Diese Position halten', 'move-closer': 'Etwas näher kommen', 'move-further': 'Etwas weiter weg bewegen',
  complete: 'Für das Selfie geradeaus schauen', capturing: 'Selfie wird aufgenommen…', hold: 'Kurz halten', step: 'Schritt', of: 'von',
  challengeList: 'Bewegungen für die Aufnahme', faceProgress: 'Fortschritt beim Halten der Position', returnCenter: 'Zurück zur Mitte',
  automaticCapture: 'Ihr Foto wird automatisch aufgenommen.',
  finishingVideo: 'Video wird vorbereitet…',
  videoReviewTitle: 'Prüfen Sie Ihr Video', videoReviewBody: 'Ihr Gesicht sollte durchgehend klar erkennbar sein.',
  videoAlt: 'Ihr aufgenommenes Gesichtsvideo', videoRetake: 'Erneut aufnehmen',
  videoUnsupported: 'Dieser Browser kann kein Gesichtsvideo aufnehmen. Verwenden Sie einen unterstützten Browser und versuchen Sie es erneut.',
  videoRecordingFailed: 'Das Video konnte nicht aufgenommen werden. Versuchen Sie es erneut.',
  videoTooLarge: 'Das Video hat seine Größenbegrenzung erreicht. Versuchen Sie es erneut und folgen Sie zügig der Anleitung.',
  videoRecordingTimeout: 'Die Videoaufnahme hat zu lange gedauert. Versuchen Sie es erneut und folgen Sie der Anleitung.',
  reviewTitle: 'Prüfen Sie Ihr Selfie', reviewBody: 'Ihr Gesicht sollte klar und gut erkennbar sein.',
  reviewEyebrow: 'SELFIE PRÜFEN', selfieAlt: 'Ihr aufgenommenes Selfie', photoReady: 'Foto bereit',
  photoReadyBody: 'Bestätigen Sie Ihr Selfie oder wiederholen Sie die Aufnahme.',
  submittingTitle: 'Aufnahme wird gesendet', submittingBody: 'Lassen Sie diese Seite bitte kurz geöffnet.',
  processingTitle: 'Aufnahme wird vorbereitet', matchingTitle: 'Ihre Fotos werden verglichen', matchingBody: 'Der Vergleich läuft auf Ihrem Gerät. Dies kann einen Moment dauern.',
  faceMatch: 'Die Gesichter sehen ähnlich aus', faceNoMatch: 'Die Gesichter stimmen nicht überein', faceInconclusive: 'Die Fotos konnten nicht zuverlässig verglichen werden',
  faceMatchBody: 'Fotoähnlichkeit ist ein Teil einer Identitätsprüfung.', faceMatchSimulation: 'Im Simulationsmodus wird der Gesichtsvergleich übersprungen.',
  matchingErrorBody: 'Der Vergleich konnte nicht abgeschlossen werden. Ihre Fotos bleiben für einen erneuten Versuch erhalten.', faceComparisonUnavailable: 'Der Fotovergleich ist nicht verfügbar. Versuchen Sie es erneut oder bitten Sie um Hilfe.',
  resultTitle: 'Ihre Aufnahme ist abgeschlossen.', resultBody: 'Ihre Aufnahme ist für den nächsten Schritt bereit.', resultStatus: 'Aufnahme abgeschlossen',
  resultEyebrow: 'AUFNAHME ABGESCHLOSSEN', errorTitle: 'Versuchen wir es erneut.', cameraErrorBody: 'Die Aufnahme konnte nicht abgeschlossen werden. Beachten Sie den Hinweis unten und versuchen Sie es erneut.',
  submissionErrorBody: 'Die Aufnahme konnte nicht gesendet werden. Sie bleibt für einen erneuten Versuch erhalten.',
  permissionDenied: 'Der Kamerazugriff wurde abgelehnt. Erlauben Sie den Zugriff im Browser und versuchen Sie es erneut.',
  cameraMissing: 'Keine geeignete Kamera gefunden. Schließen Sie eine Kamera an und versuchen Sie es erneut.',
  cameraBusy: 'Die Kamera ist nicht verfügbar. Schließen Sie andere Apps, die darauf zugreifen.',
  cameraUnsupported: 'Die Kamera benötigt einen unterstützten Browser und eine sichere HTTPS-Verbindung.',
  cameraTimeout: 'Die Aufnahme hat zu lange gedauert. Versuchen Sie es bei gutem Licht erneut.',
  simulation: 'SIMULATION · NUR DEMO', simulationBody: 'Künstliche Bewegungen und ein generiertes Demobild. Keine Kamera, Identitäts- oder Lebendigkeitsprüfung.',
  simulationStep: 'Bewegung simulieren', simulationStart: 'Simulation starten', simulationFace: 'DEMO-GESICHT',
  simulationIdleBody: 'Starten Sie die Simulation, wenn Sie bereit sind.',
  cancelledTitle: 'Aufnahme abgebrochen', cancelledBody: 'Sie können dieses Fenster schließen.', configError: 'Ungültige Konfiguration',
  documentSelectTitle: 'Dokument auswählen', documentSelectBody: 'Verwenden Sie ein gültiges Originaldokument.',
  documentTypeIdCard: 'Personalausweis', documentTypeDriversLicense: 'Führerschein', documentTypePassport: 'Reisepass', documentFrontAndBack: 'Vorder- und Rückseite', documentPhotoPage: 'Fotoseite',
  documentFrontTitle: 'Vorderseite fotografieren', documentFrontBody: 'Alle vier Ecken müssen sichtbar sein. Vermeiden Sie Reflexionen.',
  documentBackTitle: 'Rückseite fotografieren', documentBackBody: 'Drehen Sie Ihr Dokument um. Alle vier Ecken müssen sichtbar sein.',
  documentPassportTitle: 'Fotoseite fotografieren', documentCameraBody: 'Halten Sie Ihr Dokument im Rahmen. Vermeiden Sie Reflexionen.',
  documentReviewTitle: 'Foto prüfen', documentReviewBody: 'Alle Angaben müssen klar und gut lesbar sein.',
  documentFrontAlt: 'Foto der Vorderseite Ihres Dokuments', documentBackAlt: 'Foto der Rückseite Ihres Dokuments',
  documentContinue: 'Weiter', documentStartCamera: 'Kamera öffnen', documentStartDemo: 'Weiter', documentTakePhoto: 'Foto aufnehmen', documentRetake: 'Foto wiederholen', documentConfirm: 'Sieht gut aus',
  documentCaptureFailed: 'Das Dokument konnte nicht aufgenommen werden. Versuchen Sie es erneut.', documentCameraUnavailable: 'Die Dokumentkamera ist nicht verfügbar. Versuchen Sie es erneut.',
  documentSearching: 'Halten Sie alle vier Ecken im Rahmen.', documentOutside: 'Bewegen Sie das ganze Dokument in den Rahmen.', documentTooSmall: 'Kommen Sie etwas näher.',
  documentDark: 'Sorgen Sie für helles, gleichmäßiges Licht.', documentGlare: 'Neigen Sie das Dokument leicht gegen Reflexionen.', documentBlur: 'Halten Sie ruhig und lassen Sie die Kamera scharfstellen.',
  documentHoldStill: 'Kurz ruhig halten…', documentReady: 'Gut erkennbar. Nehmen Sie das Foto auf.', documentGuidanceUnavailable: 'Alle vier Ecken müssen sichtbar sein. Prüfen Sie das Foto nach der Aufnahme.',
  documentAutoHoldStill: 'Ruhig halten… das Foto wird automatisch aufgenommen.', documentAutoReady: 'Das Foto wird automatisch aufgenommen…', documentAutoProgress: 'Automatische Fotoaufnahme',
};

export function getStrings(locale: 'en' | 'de' = 'en', overrides?: Partial<Record<string, string>>): Record<string, string> {
  const result = { ...english, ...(locale === 'de' ? german : {}) };
  for (const [key, value] of Object.entries(overrides ?? {})) if (typeof value === 'string') result[key] = value;
  return result;
}
